[package]
name = "ic_sis_provider"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.9.11"
ic-cdk = "0.11.3"
ic-cdk-macros = "0.8.1"
ic_sis = "0.1.1"
ic-certified-map = "0.4.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_bytes = "0.11.12"
serde_cbor = "0.11.2"
serde_json = "1.0.105"
ic-stable-structures = "0.6.0"

[dev-dependencies]
tokio = { version = "1.32.0", features = ["full"] }
rand = "0.8.5"
hex = "0.4.3"

[lib]
crate-type = ["cdylib"]