package]
name = "ic_sis"
version = "0.0.1"
edition = "2025"
authors = ["Azizbek Khalilov <azizbek@talentum.id>"]
description = "Integrate Sui wallet-based authentication (SIS) with applications on the Internet Computer (ICP) platform."
license = "MIT"
homepage = "https://github.com/Talentum-id/ic_sis"
repository = "https://github.com/Talentum-id/ic_sis"
keywords = ["siu", "wallet", "internet-computer", "authentication", "sis"]
categories = ["authentication", "cryptography::cryptocurrencies"]

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.125"
serde_bytes = "0.11.15"
serde_cbor = "0.11.2"
candid = "0.10.9"
hex = "0.4.3"
ic-cdk = "0.15.1"
ic-cdk-timers = { version = "0.9.0" }
ic-certified-map = "0.4.0"
url = "2.4.1"
time = { version = "0.3.36", features = ["formatting"] }
rand_chacha = { version = "0.3.1" }
getrandom = { version = "0.2.15", features = ["custom"] }
k256 = "0.13.3"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
sha2 = "0.9.9"
simple_asn1 = "0.6.2"

[dev-dependencies]
ethers = "2.0.14"
tokio = { version = "1.13.1", features = ["full"] }
rand = "0.8.5"
hex-literal = "0.2.2"